import Head from 'next/head'
import { useStore } from '../store/index.js'
import styles from '../styles/Home.module.css'

export default function Home() {
  const {isLoading, setIsLoading} = useStore()
  const selectedSites = []

  async function execCommand() {
    if (!isLoading) {
      // Set loading state to true to disable button
      setIsLoading(true)
      // Execute command to run Cypress tests 
      await fetch("/api/execute", {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        // Pass selected sites to Cypress tests as JSON string
        body: JSON.stringify(selectedSites)
      }).then((res) => {
        console.log("wait for whole req");
        return res.json();
      }).then((resData) => {
        // Set loading state to false to enable button
        console.log("req send successfully");
        setIsLoading(false)

        // note = null;
      }).catch((error) => {
        // note = null;
        // Set loading state to false to enable button because of error
        console.log(error.message);
        setIsLoading(false)
        // alert(error.message);
      });
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started with testing {' '}
          {/* Button to execute the test by api */}
          <button className={styles.btn} onClick={() => execCommand()}>Test All</button>
        </p>
      </main>
    </div>
  )
}
